// <auto-generated />
using System;
using CastingRadar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CastingRadar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CastingRadarDbContext))]
    [Migration("20260408130000_AddIsHidden")]
    partial class AddIsHidden
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CastingRadar.Domain.Entities.CastingCall", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AgeRange").HasColumnType("text");
                    b.Property<string>("ContentHash").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("Deadline").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsApplied").HasColumnType("boolean");
                    b.Property<bool>("IsFavorite").HasColumnType("boolean");
                    b.Property<bool>("IsHidden").HasColumnType("boolean");
                    b.Property<bool>("IsPaid").HasColumnType("boolean");
                    b.Property<string>("Location").HasColumnType("text");
                    b.Property<string>("Region").IsRequired().HasColumnType("text");
                    b.Property<string>("RequiredGender").HasColumnType("text");
                    b.Property<string>("Requirements").HasColumnType("text");
                    b.Property<DateTime>("ScrapedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("SourceName").IsRequired().HasColumnType("text");
                    b.Property<string>("SourceUrl").IsRequired().HasColumnType("text");
                    b.Property<string>("Title").IsRequired().HasColumnType("text");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("ContentHash").IsUnique();
                    b.ToTable("CastingCalls");
                });

            modelBuilder.Entity("CastingRadar.Domain.Entities.Source", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<int>("ErrorCount").HasColumnType("integer");
                    b.Property<bool>("IsEnabled").HasColumnType("boolean");
                    b.Property<DateTime?>("LastScrapedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<string>("Region").IsRequired().HasColumnType("text");
                    b.Property<string>("Url").HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("Sources");
                });

            modelBuilder.Entity("CastingRadar.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Gender").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("LastVisitedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("PreferredRegions").IsRequired().HasColumnType("text");
                    b.Property<string>("PreferredTypes").IsRequired().HasColumnType("text");
                    b.Property<int?>("ScenicAge").HasColumnType("integer");
                    b.Property<string>("TelegramChatId").HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
